/**
 * Shared styles for Auth flow: Login, OTP, Location, User Details, KYC steps.
 */
import { StyleSheet, Dimensions } from 'react-native';
import { colors, fonts } from '../../lib/theme';

const { width: SCREEN_WIDTH, height: SCREEN_HEIGHT } = Dimensions.get('window');
const clamp = (min, pref, max) => Math.max(min, Math.min(max, pref));
const CONTENT_MAX_WIDTH = clamp(320, SCREEN_WIDTH - 32, 420);
const HEADER_HEIGHT = clamp(112, SCREEN_HEIGHT * 0.16, 148);

export const authStyles = StyleSheet.create({
  signInContainer: { flex: 1, backgroundColor: '#FFFFFF' },
  signInScroll: { flexGrow: 1, paddingBottom: 24, backgroundColor: '#FFFFFF' },

  // Image-1 layout: colored top background + white rounded card.
  signInBackdrop: { flex: 1, backgroundColor: '#FFFFFF' },
  signInCard: { width: '100%', backgroundColor: '#FFFFFF' },

  // Legacy header kept for other screens (if any still use it).
  signInHeader: {
    width: '100%',
    minHeight: HEADER_HEIGHT,
    marginTop: 7,
    backgroundColor: '#EFF6FF',
    borderBottomWidth: 1,
    borderBottomColor: '#DBEAFE',
    borderBottomLeftRadius: 35,
    borderBottomRightRadius: 35,
    paddingTop: 42,
    paddingHorizontal: 21,
    paddingBottom: 1,
    shadowColor: 'rgba(0, 0, 0, 0.1)',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 1,
    shadowRadius: 3,
    elevation: 2,
  },
  signInHeaderInner: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    maxWidth: '100%',
    height: 40,
    gap: 10.5,
    alignSelf: 'stretch',
  },
  signInLogoBox: {
    width: 35,
    height: 35,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#BEDBFF',
    borderRadius: 14.5,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: 'rgba(0, 0, 0, 0.1)',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 1,
    shadowRadius: 3,
    elevation: 2,
  },
  signInLogoIcon: { width: 21, height: 21 },
  signInBrandText: {
    fontFamily: fonts.extraBold || 'Inter',
    fontSize: 17.5,
    lineHeight: 24,
    fontWeight: '700',
    color: '#1F2A44',
    letterSpacing: -0.4375,
    textAlign: 'center',
  },

  // Match OTP screen spacing/theme so auth feels consistent.
  signInMain: {
    paddingTop: 28,
    paddingBottom: 35,
    paddingHorizontal: 21,
    maxWidth: CONTENT_MAX_WIDTH,
    width: '100%',
    alignSelf: 'center',
    flex: 1,
  },
  signInTitle: {
    fontFamily: fonts.bold || 'Arial',
    fontSize: 21,
    fontWeight: '700',
    lineHeight: 28,
    textAlign: 'center',
    color: '#1F2A44',
    marginBottom: 10.5,
  },
  signInSubtitle: {
    fontFamily: fonts.regular || 'Arial',
    fontSize: 14,
    lineHeight: 21,
    textAlign: 'center',
    color: '#6A7282',
    marginBottom: 28,
  },
  signInTopTitle: {
    fontFamily: fonts.bold || 'Arial',
    fontSize: 26,
    fontWeight: '800',
    lineHeight: 32,
    textAlign: 'center',
    color: '#FFFFFF',
    marginTop: 12,
    marginBottom: 6,
  },
  signInTopSubtitle: {
    fontFamily: fonts.regular || 'Arial',
    fontSize: 14,
    lineHeight: 20,
    textAlign: 'center',
    color: 'rgba(255,255,255,0.85)',
    marginBottom: 2,
  },
  signInChooseMethodLabel: {
    fontFamily: fonts.regular || 'Arial',
    fontSize: 14,
    lineHeight: 20,
    color: '#6B7280',
    marginBottom: 10,
  },
  signInModeTabs: {
    flexDirection: 'row',
    backgroundColor: '#F3F4F6',
    borderRadius: 16,
    padding: 4,
    marginBottom: 12,
  },
  signInModeTab: {
    flex: 1,
    paddingVertical: 11,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  signInModeTabActive: {
    backgroundColor: '#1F2A44',
    shadowColor: 'rgba(31, 42, 68, 0.25)',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 1,
    shadowRadius: 12,
    elevation: 3,
  },
  signInModeTabText: {
    fontFamily: fonts.bold || 'Arial',
    fontSize: 14,
    fontWeight: '700',
    color: '#111827',
  },
  signInModeTabTextActive: {
    color: '#FFFFFF',
  },
  signInForm: { gap: 7 },
  signInLabel: {
    fontFamily: fonts.regular || 'Arial',
    fontSize: 14,
    lineHeight: 21,
    color: '#1F2A44',
  },
  signInInputWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#E8ECF0',
    borderRadius: 14.5,
    backgroundColor: '#FFFFFF',
    overflow: 'hidden',
    minHeight: 47.5,
    shadowColor: 'rgba(255, 255, 255, 0.9)',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1,
    shadowRadius: 6,
    elevation: 2,
  },
  signInInputWrapGlow: {
    borderColor: '#F2C94C',
    shadowColor: 'rgba(242, 201, 76, 0.55)',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1,
    shadowRadius: 10,
    elevation: 4,
  },
  signInInputWrapError: { borderColor: colors.error },
  signInCountrySelector: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 14,
    paddingVertical: 12,
    gap: 8,
    backgroundColor: '#FFFFFF',
    borderRightWidth: 1,
    borderRightColor: '#E5E7EB',
    minWidth: 100,
  },
  // On some Android builds, setting `color` on emoji flags can force monochrome rendering.
  // Leave emoji flags uncolored, but ensure the dial code/text is solid black.
  signInCountryFlag: { fontSize: 17.5, lineHeight: 24, opacity: 1 },
  signInCountryCode: { fontSize: 14, lineHeight: 21, color: '#000000', opacity: 1, fontFamily: fonts.regular || 'Arial' },
  signInChevron: { fontSize: 10, color: '#99A1AF' },
  signInPhoneInput: {
    flex: 1,
    paddingVertical: 14,
    paddingHorizontal: 10.5,
    fontSize: 12.25,
    lineHeight: 14,
    fontFamily: fonts.regular || 'Arial',
    color: '#000000',
    backgroundColor: '#FFFFFF',
  },
  signInInvalidText: { fontSize: 13, color: colors.error, marginTop: 4 },
  signInErrorText: { fontSize: 14, color: colors.error, marginTop: 4, marginBottom: 4 },
  signInChannelInlineRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 8,
    gap: 6,
  },
  signInChannelInlineText: {
    fontFamily: fonts.regular || 'Arial',
    fontSize: 12,
    color: '#6B7280',
    textDecorationLine: 'none',
  },
  signInChannelInlineTextActive: {
    color: '#1F2937',
    textDecorationLine: 'underline',
  },
  signInChannelInlineSeparator: {
    fontSize: 12,
    color: '#9CA3AF',
  },
  signInButton: {
    width: '100%',
    height: 49,
    backgroundColor: '#1F2A44',
    borderRadius: 14.5,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 28,
    shadowColor: 'rgba(28, 57, 142, 0.1)',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 1,
    shadowRadius: 15,
    elevation: 4,
  },
  signInButtonDisabled: {
    opacity: 1,
    backgroundColor: '#9CA3AF',
    shadowOpacity: 0,
    shadowRadius: 0,
    elevation: 0,
  },
  signInButtonText: {
    fontFamily: fonts.bold || 'Arial',
    fontSize: 15.75,
    fontWeight: '700',
    lineHeight: 24,
    color: '#FFFFFF',
  },
  signInLegal: {
    fontFamily: fonts.regular || 'Arial',
    fontSize: 10.5,
    lineHeight: 17,
    textAlign: 'center',
    color: '#99A1AF',
    marginTop: 20,
    marginBottom: 16,
    paddingHorizontal: 12,
  },
  signInLegalLink: { color: '#3B82F6', textDecorationLine: 'underline' },
  signInConsentBox: {
    marginTop: 8,
  },
  signInConsentRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
  },
  signInConsentCheckbox: {
    width: 20,
    height: 20,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: '#CBD5E1',
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 1,
  },
  signInConsentCheckboxChecked: {
    backgroundColor: '#1F2A44',
    borderColor: '#1F2A44',
  },
  signInConsentCheckmark: {
    color: '#FFFFFF',
    fontSize: 13,
    lineHeight: 13,
    fontWeight: '800',
  },
  signInConsentText: {
    flex: 1,
    fontFamily: fonts.regular || 'Arial',
    fontSize: 12.25,
    lineHeight: 18,
    color: '#6B7280',
  },
  otpRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 10.5,
    width: '100%',
  },
  otpInput: {
    width: 42,
    height: 56,
    borderWidth: 2,
    borderColor: '#E8ECF0',
    borderRadius: 14.5,
    backgroundColor: '#FFFFFF',
    textAlign: 'center',
    fontSize: 22,
    fontWeight: '700',
    color: '#1F2A44',
    shadowColor: 'rgba(255, 255, 255, 0.9)',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1,
    shadowRadius: 6,
    elevation: 2,
  },
  otpInputGlow: {
    borderColor: '#F2C94C',
    shadowColor: 'rgba(242, 201, 76, 0.55)',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1,
    shadowRadius: 10,
    elevation: 4,
  },
  otpContainer: { flex: 1, backgroundColor: '#FFFFFF' },
  otpScroll: { flexGrow: 1, paddingBottom: 24 },
  otpHeader: {
    width: '100%',
    minHeight: HEADER_HEIGHT,
    marginTop: 7,
    backgroundColor: '#EFF6FF',
    borderBottomWidth: 1,
    borderBottomColor: '#DBEAFE',
    borderBottomLeftRadius: 35,
    borderBottomRightRadius: 35,
    paddingTop: 42,
    paddingHorizontal: 21,
    paddingBottom: 1,
    shadowColor: 'rgba(0, 0, 0, 0.1)',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 1,
    shadowRadius: 3,
    elevation: 2,
  },
  otpHeaderInner: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    maxWidth: '100%',
    height: 40,
    gap: 10.5,
    alignSelf: 'stretch',
  },
  otpLogoBox: {
    width: 35,
    height: 35,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#BEDBFF',
    borderRadius: 14.5,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: 'rgba(0, 0, 0, 0.1)',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 1,
    shadowRadius: 3,
    elevation: 2,
  },
  otpBrandText: {
    fontFamily: fonts.extraBold || 'Inter',
    fontSize: 17.5,
    lineHeight: 24,
    fontWeight: '700',
    color: '#1F2A44',
    letterSpacing: -0.4375,
    textAlign: 'center',
  },
  otpBackBtn: { marginTop: 24, alignItems: 'center' },
  otpBackText: { fontFamily: fonts.regular || 'Inter', fontSize: 14, color: '#99A1AF' },
  otpMain: {
    paddingTop: 28,
    paddingBottom: 35,
    paddingHorizontal: 21,
    maxWidth: CONTENT_MAX_WIDTH,
    width: '100%',
    alignSelf: 'center',
    flex: 1,
  },
  otpHeadBlock: { marginBottom: 28 },
  otpTitle: {
    fontFamily: fonts.bold || 'Arial',
    fontSize: 21,
    fontWeight: '700',
    lineHeight: 28,
    textAlign: 'center',
    color: '#1F2A44',
    marginBottom: 10.5,
  },
  otpSubtitle: {
    fontFamily: fonts.regular || 'Arial',
    fontSize: 14,
    lineHeight: 21,
    textAlign: 'center',
    color: '#6A7282',
  },
  otpInputsBlock: { gap: 28, marginBottom: 14 },
  otpErrorText: { color: colors.error, fontSize: 14, textAlign: 'center', marginBottom: 12 },
  otpButton: {
    width: '100%',
    height: 49,
    backgroundColor: '#1F2A44',
    borderRadius: 14.5,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 28,
    shadowColor: 'rgba(28, 57, 142, 0.1)',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 1,
    shadowRadius: 15,
    elevation: 4,
  },
  otpButtonDisabled: { opacity: 0.5 },
  otpButtonText: {
    fontFamily: fonts.semiBold || 'Arial',
    fontSize: 15.75,
    fontWeight: '600',
    lineHeight: 24,
    color: '#FFFFFF',
    textAlign: 'center',
  },
  otpResendWrap: { alignItems: 'center', marginTop: 28 },
  otpResendText: {
    fontFamily: fonts.regular || 'Arial',
    fontSize: 12.25,
    lineHeight: 18,
    color: '#99A1AF',
    textAlign: 'center',
  },
  otpResendLink: {
    fontFamily: fonts.regular || 'Arial',
    fontSize: 12.25,
    lineHeight: 18,
    color: '#99A1AF',
  },
  identityContainer: { flex: 1, backgroundColor: '#FFFFFF' },
  identityScroll: { flexGrow: 1, paddingBottom: 35 },
  identityBannerWrap: {
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 8,
    backgroundColor: '#EFF6FF',
  },
  identityBannerText: {
    fontSize: 13,
    color: '#1F2A44',
    textAlign: 'center',
  },
  identityHeader: {
    width: '100%',
    minHeight: clamp(128, SCREEN_HEIGHT * 0.19, 164),
    paddingTop: 42,
    paddingHorizontal: 21,
    paddingBottom: 1,
    backgroundColor: '#EFF6FF',
    borderBottomWidth: 1,
    borderBottomColor: '#DBEAFE',
    borderBottomLeftRadius: 35,
    borderBottomRightRadius: 35,
    shadowColor: 'rgba(0, 0, 0, 0.1)',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 1,
    shadowRadius: 3,
    elevation: 2,
  },
  identityHeaderContent: {
    flexDirection: 'column',
    alignItems: 'center',
    gap: 14,
    width: '100%',
    maxWidth: CONTENT_MAX_WIDTH - 32,
    height: 63.28,
    alignSelf: 'stretch',
  },
  identityHeaderInner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    flex: 1,
  },
  identityBackBtn: { padding: 8 },
  identityHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10.5,
    flex: 1,
    justifyContent: 'center',
    height: 35,
  },
  identityLogoBox: {
    width: 35,
    height: 35,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#DBEAFE',
    borderRadius: 14.5,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: 'rgba(0, 0, 0, 0.1)',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 1,
    shadowRadius: 3,
    elevation: 2,
  },
  identityHeaderTextWrap: { flexDirection: 'column', alignItems: 'flex-start', gap: 14 },
  identityHeaderRight: { width: 38 },
  identityTitle: {
    fontFamily: fonts.bold || 'Inter',
    fontSize: 17.5,
    lineHeight: 24,
    fontWeight: '700',
    color: '#1F2A44',
    letterSpacing: -0.4375,
    textAlign: 'center',
  },
  identitySubtitle: {
    fontFamily: fonts.bold || 'Inter',
    fontSize: 10,
    lineHeight: 14,
    fontWeight: '700',
    letterSpacing: 2,
    textTransform: 'uppercase',
    color: '#2B7FFF',
    opacity: 0.8,
    textAlign: 'center',
  },
  identityMain: {
    paddingTop: 35,
    paddingHorizontal: 21,
    gap: 35,
    maxWidth: CONTENT_MAX_WIDTH,
    width: '100%',
    alignSelf: 'center',
  },
  identityAvatarBlock: { alignItems: 'center', marginBottom: 0 },
  identityAvatarWrap: {
    width: 112,
    height: 112,
    borderRadius: 40,
    borderWidth: 4,
    borderColor: '#FFFFFF',
    backgroundColor: 'rgba(239, 246, 255, 0.5)',
    shadowColor: '#EFF6FF',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1,
    shadowRadius: 4,
    elevation: 8,
    overflow: 'visible',
    justifyContent: 'center',
    alignItems: 'center',
  },
  identityAvatarPlaceholder: {
    width: 104,
    height: 104,
    borderRadius: 36,
    backgroundColor: 'rgba(255,255,255,0.01)',
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
  },
  identityAvatarImage: { width: 104, height: 104, borderRadius: 36 },
  identityAvatarLetter: {
    fontFamily: fonts.bold || 'Inter',
    fontSize: 40,
    fontWeight: '700',
    color: '#1F2A44',
  },
  identityCameraBtn: {
    position: 'absolute',
    right: 0,
    bottom: 0,
    width: 35,
    height: 35,
    borderRadius: 14,
    backgroundColor: '#F2C94C',
    borderWidth: 2,
    borderColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: 'rgba(0,0,0,0.1)',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 1,
    shadowRadius: 15,
    elevation: 4,
  },
  identityHeadshotLabel: {
    fontFamily: fonts.bold || 'Inter',
    fontSize: 10,
    fontWeight: '700',
    lineHeight: 14,
    letterSpacing: 1,
    textTransform: 'uppercase',
    color: '#99A1AF',
    marginTop: 14,
  },
  identityForm: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: 21,
    width: '100%',
    maxWidth: CONTENT_MAX_WIDTH - 32,
    alignSelf: 'stretch',
  },
  identityFieldBlock: { width: '100%', alignSelf: 'stretch' },
  identityFieldLabel: {
    fontFamily: fonts.bold || 'Inter',
    fontSize: 10.5,
    lineHeight: 14,
    fontWeight: '700',
    letterSpacing: 1.05,
    textTransform: 'uppercase',
    color: '#1F2A44',
    marginLeft: 3.5,
    marginBottom: 7,
  },
  identityInputWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    height: 49,
    paddingLeft: 42,
    paddingRight: 10.5,
    paddingVertical: 3.5,
    backgroundColor: 'rgba(239, 246, 255, 0.3)',
    borderWidth: 1,
    borderColor: '#DBEAFE',
    borderRadius: 14,
  },
  identityInputIcon: { position: 'absolute', left: 14, top: 15.75 },
  identityInput: {
    flex: 1,
    fontFamily: fonts.regular || 'Inter',
    fontSize: 12.25,
    lineHeight: 18,
    fontWeight: '500',
    color: '#1F2A44',
    padding: 0,
  },
  identityErrorText: { color: colors.error, fontSize: 14, marginTop: 8 },
  identityProceedBtn: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    height: 56,
    backgroundColor: '#1F2A44',
    borderRadius: 14,
    gap: 17.5,
    shadowColor: '#DBEAFE',
    shadowOffset: { width: 0, height: 20 },
    shadowOpacity: 1,
    shadowRadius: 25,
    elevation: 6,
    marginTop: 14,
  },
  identityProceedBtnDisabled: { opacity: 0.6 },
  identityProceedText: {
    fontFamily: fonts.bold || 'Inter',
    fontSize: 15.75,
    fontWeight: '700',
    lineHeight: 24,
    color: '#FFFFFF',
    textAlign: 'center',
  },
  kycDocContainer: { flex: 1, backgroundColor: '#FFFFFF' },
  kycDocScroll: { flexGrow: 1, paddingBottom: 35 },
  kycDocScrollView: { flex: 1 },
  kycDocHeaderSubtitle: {
    fontFamily: fonts.bold || 'Inter',
    fontSize: 10,
    fontWeight: '700',
    lineHeight: 14,
    letterSpacing: 2,
    textTransform: 'uppercase',
    color: '#2B7FFF',
    textAlign: 'center',
  },
  kycDocMain: {
    paddingTop: 35,
    paddingHorizontal: 21,
    paddingBottom: 0,
    gap: 21,
    backgroundColor: '#FFFFFF',
    flex: 1,
  },
  kycDocHeadingBlock: { gap: 3.5 },
  kycDocHeading: {
    fontFamily: fonts.bold || 'Inter',
    fontSize: 17.5,
    fontWeight: '700',
    lineHeight: 24,
    color: '#1F2A44',
  },
  kycDocSubtitle: {
    fontFamily: fonts.regular || 'Inter',
    fontSize: 12.25,
    fontWeight: '400',
    lineHeight: 18,
    color: '#99A1AF',
  },
  kycDocCards: { gap: 10.5, width: '100%', maxWidth: CONTENT_MAX_WIDTH - 32 },
  kycDocCard: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 17.5,
    height: 79,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#F3F4F6',
    borderRadius: 14,
  },
  kycDocCardLeft: { flexDirection: 'row', alignItems: 'center', gap: 14, flex: 1 },
  kycDocCardIconWrap: {
    width: 42,
    height: 42,
    borderRadius: 14.5,
    backgroundColor: '#EFF6FF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  kycDocCardTextWrap: { gap: 0, flex: 1 },
  kycDocCardTitle: {
    fontFamily: fonts.bold || 'Inter',
    fontSize: 12.25,
    fontWeight: '700',
    lineHeight: 18,
    color: '#1F2A44',
  },
  kycDocCardSubtitle: {
    fontFamily: fonts.bold || 'Inter',
    fontSize: 10,
    fontWeight: '700',
    lineHeight: 14,
    letterSpacing: 1,
    textTransform: 'uppercase',
    color: '#99A1AF',
  },
  kycUploadContainer: { flex: 1, backgroundColor: '#FFFFFF' },
  kycUploadScroll: { flexGrow: 1, paddingBottom: 35 },
  kycUploadScrollView: { flex: 1 },
  kycUploadMain: {
    paddingTop: 35,
    paddingHorizontal: 21,
    paddingBottom: 0,
    gap: 28,
    backgroundColor: '#FFFFFF',
  },
  kycUploadHeadingBlock: { gap: 3.5 },
  kycUploadHeading: {
    fontFamily: fonts.bold || 'Inter',
    fontSize: 17.5,
    fontWeight: '700',
    lineHeight: 24,
    color: '#1F2A44',
  },
  kycUploadSubtitle: {
    fontFamily: fonts.regular || 'Inter',
    fontSize: 12.25,
    fontWeight: '400',
    lineHeight: 18,
    color: '#99A1AF',
  },
  kycUploadCards: { gap: 14, width: '100%', maxWidth: CONTENT_MAX_WIDTH - 32 },
  kycUploadCard: {
    width: '100%',
    maxWidth: CONTENT_MAX_WIDTH - 32,
    minHeight: 200,
    height: 200,
    backgroundColor: 'rgba(249, 250, 251, 0.5)',
    borderWidth: 2,
    borderColor: '#E5E7EB',
    borderRadius: 32,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 10.5,
    gap: 10.5,
    overflow: 'hidden',
  },
  kycUploadCardPressed: {
    borderColor: '#2B7FFF',
    backgroundColor: 'rgba(235, 246, 255, 0.6)',
  },
  kycUploadCardIconWrap: {
    width: 42,
    height: 42,
    borderRadius: 99999,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#F3F4F6',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: 'rgba(0, 0, 0, 0.1)',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 1,
    shadowRadius: 3,
    elevation: 2,
  },
  kycUploadCardLabel: {
    fontFamily: fonts.bold || 'Inter',
    fontSize: 12.25,
    fontWeight: '700',
    lineHeight: 18,
    color: '#6A7282',
  },
  kycUploadCardLabelPressed: { color: '#2B7FFF' },
  kycUploadCardImage: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    borderRadius: 30,
    resizeMode: 'contain',
  },
  kycUploadNextBtn: {
    width: '100%',
    maxWidth: CONTENT_MAX_WIDTH - 32,
    height: 56,
    backgroundColor: '#1F2A44',
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: 'rgba(0, 0, 0, 0.1)',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 1,
    shadowRadius: 15,
    elevation: 4,
  },
  kycUploadNextBtnDisabled: { opacity: 0.5 },
  kycUploadNextText: {
    fontFamily: fonts.bold || 'Inter',
    fontSize: 15.75,
    fontWeight: '700',
    lineHeight: 24,
    color: '#FFFFFF',
    textAlign: 'center',
  },
  liveBiometricsFrame: {
    width: '100%',
    maxWidth: CONTENT_MAX_WIDTH - 32,
    alignSelf: 'center',
    alignItems: 'center',
    marginTop: 14,
    marginBottom: 24,
  },
  liveBiometricsFrameInner: {
    width: '100%',
    aspectRatio: 3 / 4,
    maxHeight: 320,
    backgroundColor: '#1E3A5F',
    borderRadius: 24,
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
    position: 'relative',
  },
  liveBiometricsCamera: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    borderRadius: 24,
  },
  liveBiometricsPlaceholder: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: '#1E3A5F',
  },
  liveBiometricsFaceGuide: {
    position: 'absolute',
    width: '70%',
    aspectRatio: 1,
    borderRadius: 9999,
    borderWidth: 2,
    borderColor: 'rgba(255,255,255,0.35)',
    borderStyle: 'dashed',
    alignSelf: 'center',
    top: '50%',
    marginTop: '-35%',
  },
  liveBiometricsAnalyzing: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(30,58,95,0.9)',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 12,
  },
  liveBiometricsAnalyzingText: {
    fontFamily: fonts.bold || 'Inter',
    fontSize: 14,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  liveBiometricsCaptureBtn: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: -36,
    shadowColor: 'rgba(0,0,0,0.2)',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 1,
    shadowRadius: 12,
    elevation: 8,
  },
  liveBiometricsCaptureLabel: {
    fontFamily: fonts.bold || 'Inter',
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 1.2,
    color: '#6A7282',
    marginTop: 10,
  },
  liveBiometricsSkipLink: {
    alignSelf: 'center',
    paddingVertical: 12,
    paddingHorizontal: 16,
  },
  liveBiometricsSkipText: {
    fontFamily: fonts.bold || 'Inter',
    fontSize: 11,
    fontWeight: '600',
    letterSpacing: 0.5,
    color: '#51A2FF',
  },
  locationContainer: { flex: 1, backgroundColor: '#FFFFFF' },
  locationScroll: { flexGrow: 1, paddingBottom: 35 },
  locationScrollView: { flex: 1 },
  locationMain: {
    paddingTop: 28,
    paddingBottom: 35,
    paddingHorizontal: 21,
    maxWidth: CONTENT_MAX_WIDTH,
    width: '100%',
    alignSelf: 'center',
    gap: 28,
  },
  locationIconBlock: { alignItems: 'center', paddingTop: 28, marginBottom: 0 },
  locationIconOuter: {
    width: 140,
    height: 140,
    borderRadius: 99999,
    backgroundColor: '#EFF6FF',
    opacity: 0.51,
    justifyContent: 'center',
    alignItems: 'center',
  },
  locationIconInner: {
    width: 112,
    height: 112,
    borderRadius: 99999,
    backgroundColor: '#DBEAFE',
    justifyContent: 'center',
    alignItems: 'center',
  },
  locationCopyBlock: { gap: 14, marginBottom: 0 },
  locationTitle: {
    fontFamily: fonts.bold || 'Inter',
    fontSize: 21,
    fontWeight: '700',
    lineHeight: 28,
    textAlign: 'center',
    color: '#1F2A44',
  },
  locationParagraph: {
    fontFamily: fonts.regular || 'Inter',
    fontSize: 14,
    fontWeight: '400',
    lineHeight: 23,
    textAlign: 'center',
    color: '#6A7282',
  },
  locationButtonsBlock: { paddingTop: 21, gap: 14 },
  locationErrorText: {
    color: colors.error,
    fontSize: 14,
    textAlign: 'center',
    marginBottom: 4,
  },
  locationButtonPrimary: {
    width: '100%',
    height: 49,
    backgroundColor: '#1F2A44',
    borderRadius: 14.5,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: 'rgba(28, 57, 142, 0.1)',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 1,
    shadowRadius: 15,
    elevation: 4,
  },
  locationButtonDisabled: { opacity: 0.6 },
  locationButtonPrimaryText: {
    fontFamily: fonts.semiBold || 'Inter',
    fontSize: 15.75,
    fontWeight: '600',
    lineHeight: 24,
    color: '#FFFFFF',
    textAlign: 'center',
  },
  locationButtonSecondary: {
    width: '100%',
    height: 49,
    backgroundColor: 'transparent',
    borderRadius: 14.5,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#CBD5E1',
  },
  locationButtonSecondaryText: {
    fontFamily: fonts.semiBold || 'Inter',
    fontSize: 15.75,
    fontWeight: '600',
    lineHeight: 24,
    color: '#1F2A44',
    textAlign: 'center',
  },
  locationFooter: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 7,
    marginTop: 14,
  },
  locationFooterText: {
    fontFamily: fonts.regular || 'Inter',
    fontSize: 10.5,
    lineHeight: 14,
    color: '#99A1AF',
  },
  modalOverlay: {
    flex: 1,
    // Keep the modal overlay from covering the underlying screen with a white block.
    backgroundColor: 'transparent',
    justifyContent: 'flex-start',
  },
  modalSheet: {
    flex: 1,
    backgroundColor: colors.white,
    borderTopLeftRadius: 0,
    borderTopRightRadius: 0,
  },
  modalHeader: {
    backgroundColor: colors.headerBg,
    padding: 24,
    borderBottomWidth: 1,
    borderBottomColor: colors.headerBorder,
  },
  modalTitle: { fontSize: 18, fontWeight: '800', color: colors.primary },
  modalSubtitle: { fontSize: 10, color: colors.textLight, marginTop: 4, letterSpacing: 1 },
  modalClose: { position: 'absolute', top: 20, right: 20 },
  modalCloseText: { fontSize: 20, color: colors.primary },
  modalBody: { flex: 1 },
  modalBodyContent: { paddingHorizontal: 24, paddingTop: 18, paddingBottom: 12 },
  modalLoaderWrap: { paddingVertical: 24, alignItems: 'center' },
  modalP: { fontSize: 14, color: colors.primary, fontWeight: '600', lineHeight: 22 },
  modalFooter: {
    paddingHorizontal: 24,
    paddingTop: 6,
    paddingBottom: 16,
    borderTopWidth: 1,
    borderTopColor: colors.headerBorder,
    backgroundColor: colors.white,
  },
  modalBox: { backgroundColor: colors.borderLight, padding: 16, borderRadius: 12, marginBottom: 24 },
  modalBoxTitle: { fontSize: 10, fontWeight: '800', color: colors.primary, marginBottom: 8 },
  modalBoxP: { fontSize: 11, color: colors.textMuted },
  modalAccept: { backgroundColor: colors.primary, paddingVertical: 16, borderRadius: 16, alignItems: 'center' },
  modalAcceptText: { fontSize: 12, fontWeight: '700', color: colors.white, letterSpacing: 1 },
  pickerSheet: {
    backgroundColor: colors.white,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    overflow: 'hidden',
    flex: 1,
    alignSelf: 'stretch',
  },
  pickerHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  pickerTitle: { fontSize: 18, fontWeight: '700', color: colors.primary },
  pickerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 14,
    paddingHorizontal: 20,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.borderLight,
    gap: 12,
  },
  pickerRowActive: { backgroundColor: colors.headerBg },
  pickerFlag: { fontSize: 22 },
  pickerName: { flex: 1, fontSize: 16, color: colors.primary },
  pickerDial: { fontSize: 15, fontWeight: '600', color: colors.textMuted },
});
