/**
 * Countries with dial code, flag emoji, and phone number length validation.
 * lengths = [min, max] for national number digits only (excluding country code).
 * Default order: South Africa (+27), India (+91), US (+1), UK (+44) first, then all others.
 */
export const COUNTRIES = [
  { code: 'ZA', name: 'South Africa', dial: '+27', flag: '🇿🇦', lengths: [9, 9] },
  { code: 'IN', name: 'India', dial: '+91', flag: '🇮🇳', lengths: [10, 10] },
  { code: 'US', name: 'United States', dial: '+1', flag: '🇺🇸', lengths: [10, 10] },
  { code: 'GB', name: 'United Kingdom', dial: '+44', flag: '🇬🇧', lengths: [10, 11] },
  { code: 'AF', name: 'Afghanistan', dial: '+93', flag: '🇦🇫', lengths: [9, 9] },
  { code: 'AL', name: 'Albania', dial: '+355', flag: '🇦🇱', lengths: [8, 9] },
  { code: 'DZ', name: 'Algeria', dial: '+213', flag: '🇩🇿', lengths: [8, 9] },
  { code: 'AD', name: 'Andorra', dial: '+376', flag: '🇦🇩', lengths: [6, 9] },
  { code: 'AO', name: 'Angola', dial: '+244', flag: '🇦🇴', lengths: [9, 9] },
  { code: 'AG', name: 'Antigua and Barbuda', dial: '+1268', flag: '🇦🇬', lengths: [10, 10] },
  { code: 'AR', name: 'Argentina', dial: '+54', flag: '🇦🇷', lengths: [10, 11] },
  { code: 'AM', name: 'Armenia', dial: '+374', flag: '🇦🇲', lengths: [8, 8] },
  { code: 'AU', name: 'Australia', dial: '+61', flag: '🇦🇺', lengths: [9, 9] },
  { code: 'AT', name: 'Austria', dial: '+43', flag: '🇦🇹', lengths: [10, 13] },
  { code: 'AZ', name: 'Azerbaijan', dial: '+994', flag: '🇦🇿', lengths: [9, 9] },
  { code: 'BS', name: 'Bahamas', dial: '+1242', flag: '🇧🇸', lengths: [10, 10] },
  { code: 'BH', name: 'Bahrain', dial: '+973', flag: '🇧🇭', lengths: [8, 8] },
  { code: 'BD', name: 'Bangladesh', dial: '+880', flag: '🇧🇩', lengths: [10, 10] },
  { code: 'BB', name: 'Barbados', dial: '+1246', flag: '🇧🇧', lengths: [10, 10] },
  { code: 'BY', name: 'Belarus', dial: '+375', flag: '🇧🇾', lengths: [9, 9] },
  { code: 'BE', name: 'Belgium', dial: '+32', flag: '🇧🇪', lengths: [8, 9] },
  { code: 'BZ', name: 'Belize', dial: '+501', flag: '🇧🇿', lengths: [7, 7] },
  { code: 'BJ', name: 'Benin', dial: '+229', flag: '🇧🇯', lengths: [8, 9] },
  { code: 'BT', name: 'Bhutan', dial: '+975', flag: '🇧🇹', lengths: [8, 8] },
  { code: 'BO', name: 'Bolivia', dial: '+591', flag: '🇧🇴', lengths: [9, 9] },
  { code: 'BA', name: 'Bosnia and Herzegovina', dial: '+387', flag: '🇧🇦', lengths: [8, 8] },
  { code: 'BW', name: 'Botswana', dial: '+267', flag: '🇧🇼', lengths: [7, 8] },
  { code: 'BR', name: 'Brazil', dial: '+55', flag: '🇧🇷', lengths: [10, 11] },
  { code: 'BN', name: 'Brunei', dial: '+673', flag: '🇧🇳', lengths: [7, 7] },
  { code: 'BG', name: 'Bulgaria', dial: '+359', flag: '🇧🇬', lengths: [8, 9] },
  { code: 'BF', name: 'Burkina Faso', dial: '+226', flag: '🇧🇫', lengths: [8, 8] },
  { code: 'BI', name: 'Burundi', dial: '+257', flag: '🇧🇮', lengths: [8, 8] },
  { code: 'KH', name: 'Cambodia', dial: '+855', flag: '🇰🇭', lengths: [8, 9] },
  { code: 'CM', name: 'Cameroon', dial: '+237', flag: '🇨🇲', lengths: [8, 8] },
  { code: 'CA', name: 'Canada', dial: '+1', flag: '🇨🇦', lengths: [10, 10] },
  { code: 'CV', name: 'Cape Verde', dial: '+238', flag: '🇨🇻', lengths: [7, 7] },
  { code: 'CF', name: 'Central African Republic', dial: '+236', flag: '🇨🇫', lengths: [8, 8] },
  { code: 'TD', name: 'Chad', dial: '+235', flag: '🇹🇩', lengths: [8, 8] },
  { code: 'CL', name: 'Chile', dial: '+56', flag: '🇨🇱', lengths: [9, 9] },
  { code: 'CN', name: 'China', dial: '+86', flag: '🇨🇳', lengths: [10, 11] },
  { code: 'CO', name: 'Colombia', dial: '+57', flag: '🇨🇴', lengths: [10, 10] },
  { code: 'KM', name: 'Comoros', dial: '+269', flag: '🇰🇲', lengths: [7, 7] },
  { code: 'CG', name: 'Congo', dial: '+242', flag: '🇨🇬', lengths: [9, 9] },
  { code: 'CD', name: 'Congo (DRC)', dial: '+243', flag: '🇨🇩', lengths: [9, 9] },
  { code: 'CR', name: 'Costa Rica', dial: '+506', flag: '🇨🇷', lengths: [8, 8] },
  { code: 'HR', name: 'Croatia', dial: '+385', flag: '🇭🇷', lengths: [8, 9] },
  { code: 'CU', name: 'Cuba', dial: '+53', flag: '🇨🇺', lengths: [8, 8] },
  { code: 'CY', name: 'Cyprus', dial: '+357', flag: '🇨🇾', lengths: [8, 8] },
  { code: 'CZ', name: 'Czech Republic', dial: '+420', flag: '🇨🇿', lengths: [9, 9] },
  { code: 'DK', name: 'Denmark', dial: '+45', flag: '🇩🇰', lengths: [8, 8] },
  { code: 'DJ', name: 'Djibouti', dial: '+253', flag: '🇩🇯', lengths: [8, 8] },
  { code: 'DM', name: 'Dominica', dial: '+1767', flag: '🇩🇲', lengths: [10, 10] },
  { code: 'DO', name: 'Dominican Republic', dial: '+1809', flag: '🇩🇴', lengths: [10, 10] },
  { code: 'EC', name: 'Ecuador', dial: '+593', flag: '🇪🇨', lengths: [9, 9] },
  { code: 'EG', name: 'Egypt', dial: '+20', flag: '🇪🇬', lengths: [9, 10] },
  { code: 'SV', name: 'El Salvador', dial: '+503', flag: '🇸🇻', lengths: [8, 8] },
  { code: 'GQ', name: 'Equatorial Guinea', dial: '+240', flag: '🇬🇶', lengths: [9, 9] },
  { code: 'ER', name: 'Eritrea', dial: '+291', flag: '🇪🇷', lengths: [7, 7] },
  { code: 'EE', name: 'Estonia', dial: '+372', flag: '🇪🇪', lengths: [7, 8] },
  { code: 'SZ', name: 'Eswatini', dial: '+268', flag: '🇸🇿', lengths: [8, 8] },
  { code: 'ET', name: 'Ethiopia', dial: '+251', flag: '🇪🇹', lengths: [9, 9] },
  { code: 'FJ', name: 'Fiji', dial: '+679', flag: '🇫🇯', lengths: [7, 7] },
  { code: 'FI', name: 'Finland', dial: '+358', flag: '🇫🇮', lengths: [9, 10] },
  { code: 'FR', name: 'France', dial: '+33', flag: '🇫🇷', lengths: [9, 9] },
  { code: 'GA', name: 'Gabon', dial: '+241', flag: '🇬🇦', lengths: [8, 8] },
  { code: 'GM', name: 'Gambia', dial: '+220', flag: '🇬🇲', lengths: [7, 7] },
  { code: 'GE', name: 'Georgia', dial: '+995', flag: '🇬🇪', lengths: [9, 9] },
  { code: 'DE', name: 'Germany', dial: '+49', flag: '🇩🇪', lengths: [10, 11] },
  { code: 'GH', name: 'Ghana', dial: '+233', flag: '🇬🇭', lengths: [9, 9] },
  { code: 'GR', name: 'Greece', dial: '+30', flag: '🇬🇷', lengths: [10, 10] },
  { code: 'GD', name: 'Grenada', dial: '+1473', flag: '🇬🇩', lengths: [10, 10] },
  { code: 'GT', name: 'Guatemala', dial: '+502', flag: '🇬🇹', lengths: [8, 8] },
  { code: 'GN', name: 'Guinea', dial: '+224', flag: '🇬🇳', lengths: [9, 9] },
  { code: 'GW', name: 'Guinea-Bissau', dial: '+245', flag: '🇬🇼', lengths: [7, 7] },
  { code: 'GY', name: 'Guyana', dial: '+592', flag: '🇬🇾', lengths: [7, 7] },
  { code: 'HT', name: 'Haiti', dial: '+509', flag: '🇭🇹', lengths: [8, 8] },
  { code: 'HN', name: 'Honduras', dial: '+504', flag: '🇭🇳', lengths: [8, 8] },
  { code: 'HK', name: 'Hong Kong', dial: '+852', flag: '🇭🇰', lengths: [8, 8] },
  { code: 'HU', name: 'Hungary', dial: '+36', flag: '🇭🇺', lengths: [8, 9] },
  { code: 'IS', name: 'Iceland', dial: '+354', flag: '🇮🇸', lengths: [7, 7] },
  { code: 'ID', name: 'Indonesia', dial: '+62', flag: '🇮🇩', lengths: [9, 12] },
  { code: 'IR', name: 'Iran', dial: '+98', flag: '🇮🇷', lengths: [10, 10] },
  { code: 'IQ', name: 'Iraq', dial: '+964', flag: '🇮🇶', lengths: [9, 10] },
  { code: 'IE', name: 'Ireland', dial: '+353', flag: '🇮🇪', lengths: [9, 9] },
  { code: 'IL', name: 'Israel', dial: '+972', flag: '🇮🇱', lengths: [8, 9] },
  { code: 'IT', name: 'Italy', dial: '+39', flag: '🇮🇹', lengths: [9, 11] },
  { code: 'CI', name: 'Ivory Coast', dial: '+225', flag: '🇨🇮', lengths: [10, 10] },
  { code: 'JM', name: 'Jamaica', dial: '+1876', flag: '🇯🇲', lengths: [10, 10] },
  { code: 'JP', name: 'Japan', dial: '+81', flag: '🇯🇵', lengths: [10, 10] },
  { code: 'JO', name: 'Jordan', dial: '+962', flag: '🇯🇴', lengths: [9, 9] },
  { code: 'KZ', name: 'Kazakhstan', dial: '+7', flag: '🇰🇿', lengths: [10, 10] },
  { code: 'KE', name: 'Kenya', dial: '+254', flag: '🇰🇪', lengths: [9, 9] },
  { code: 'KI', name: 'Kiribati', dial: '+686', flag: '🇰🇮', lengths: [8, 8] },
  { code: 'KW', name: 'Kuwait', dial: '+965', flag: '🇰🇼', lengths: [8, 8] },
  { code: 'KG', name: 'Kyrgyzstan', dial: '+996', flag: '🇰🇬', lengths: [9, 9] },
  { code: 'LA', name: 'Laos', dial: '+856', flag: '🇱🇦', lengths: [8, 9] },
  { code: 'LV', name: 'Latvia', dial: '+371', flag: '🇱🇻', lengths: [8, 8] },
  { code: 'LB', name: 'Lebanon', dial: '+961', flag: '🇱🇧', lengths: [7, 8] },
  { code: 'LS', name: 'Lesotho', dial: '+266', flag: '🇱🇸', lengths: [8, 8] },
  { code: 'LR', name: 'Liberia', dial: '+231', flag: '🇱🇷', lengths: [7, 9] },
  { code: 'LY', name: 'Libya', dial: '+218', flag: '🇱🇾', lengths: [9, 10] },
  { code: 'LI', name: 'Liechtenstein', dial: '+423', flag: '🇱🇮', lengths: [7, 7] },
  { code: 'LT', name: 'Lithuania', dial: '+370', flag: '🇱🇹', lengths: [8, 8] },
  { code: 'LU', name: 'Luxembourg', dial: '+352', flag: '🇱🇺', lengths: [9, 9] },
  { code: 'MO', name: 'Macau', dial: '+853', flag: '🇲🇴', lengths: [8, 8] },
  { code: 'MG', name: 'Madagascar', dial: '+261', flag: '🇲🇬', lengths: [9, 9] },
  { code: 'MW', name: 'Malawi', dial: '+265', flag: '🇲🇼', lengths: [7, 9] },
  { code: 'MY', name: 'Malaysia', dial: '+60', flag: '🇲🇾', lengths: [9, 10] },
  { code: 'MV', name: 'Maldives', dial: '+960', flag: '🇲🇻', lengths: [7, 7] },
  { code: 'ML', name: 'Mali', dial: '+223', flag: '🇲🇱', lengths: [8, 8] },
  { code: 'MT', name: 'Malta', dial: '+356', flag: '🇲🇹', lengths: [8, 8] },
  { code: 'MH', name: 'Marshall Islands', dial: '+692', flag: '🇲🇭', lengths: [7, 7] },
  { code: 'MR', name: 'Mauritania', dial: '+222', flag: '🇲🇷', lengths: [8, 8] },
  { code: 'MU', name: 'Mauritius', dial: '+230', flag: '🇲🇺', lengths: [8, 8] },
  { code: 'MX', name: 'Mexico', dial: '+52', flag: '🇲🇽', lengths: [10, 10] },
  { code: 'FM', name: 'Micronesia', dial: '+691', flag: '🇫🇲', lengths: [7, 7] },
  { code: 'MD', name: 'Moldova', dial: '+373', flag: '🇲🇩', lengths: [8, 8] },
  { code: 'MC', name: 'Monaco', dial: '+377', flag: '🇲🇨', lengths: [8, 9] },
  { code: 'MN', name: 'Mongolia', dial: '+976', flag: '🇲🇳', lengths: [8, 8] },
  { code: 'ME', name: 'Montenegro', dial: '+382', flag: '🇲🇪', lengths: [8, 8] },
  { code: 'MA', name: 'Morocco', dial: '+212', flag: '🇲🇦', lengths: [9, 9] },
  { code: 'MZ', name: 'Mozambique', dial: '+258', flag: '🇲🇿', lengths: [9, 9] },
  { code: 'MM', name: 'Myanmar', dial: '+95', flag: '🇲🇲', lengths: [8, 10] },
  { code: 'NA', name: 'Namibia', dial: '+264', flag: '🇳🇦', lengths: [9, 9] },
  { code: 'NR', name: 'Nauru', dial: '+674', flag: '🇳🇷', lengths: [7, 7] },
  { code: 'NP', name: 'Nepal', dial: '+977', flag: '🇳🇵', lengths: [10, 10] },
  { code: 'NL', name: 'Netherlands', dial: '+31', flag: '🇳🇱', lengths: [9, 9] },
  { code: 'NZ', name: 'New Zealand', dial: '+64', flag: '🇳🇿', lengths: [9, 10] },
  { code: 'NI', name: 'Nicaragua', dial: '+505', flag: '🇳🇮', lengths: [8, 8] },
  { code: 'NE', name: 'Niger', dial: '+227', flag: '🇳🇪', lengths: [8, 8] },
  { code: 'NG', name: 'Nigeria', dial: '+234', flag: '🇳🇬', lengths: [10, 11] },
  { code: 'MK', name: 'North Macedonia', dial: '+389', flag: '🇲🇰', lengths: [8, 8] },
  { code: 'NO', name: 'Norway', dial: '+47', flag: '🇳🇴', lengths: [8, 8] },
  { code: 'OM', name: 'Oman', dial: '+968', flag: '🇴🇲', lengths: [8, 8] },
  { code: 'PK', name: 'Pakistan', dial: '+92', flag: '🇵🇰', lengths: [10, 10] },
  { code: 'PW', name: 'Palau', dial: '+680', flag: '🇵🇼', lengths: [7, 7] },
  { code: 'PS', name: 'Palestine', dial: '+970', flag: '🇵🇸', lengths: [9, 9] },
  { code: 'PA', name: 'Panama', dial: '+507', flag: '🇵🇦', lengths: [8, 8] },
  { code: 'PG', name: 'Papua New Guinea', dial: '+675', flag: '🇵🇬', lengths: [8, 8] },
  { code: 'PY', name: 'Paraguay', dial: '+595', flag: '🇵🇾', lengths: [9, 9] },
  { code: 'PE', name: 'Peru', dial: '+51', flag: '🇵🇪', lengths: [9, 9] },
  { code: 'PH', name: 'Philippines', dial: '+63', flag: '🇵🇭', lengths: [10, 10] },
  { code: 'PL', name: 'Poland', dial: '+48', flag: '🇵🇱', lengths: [9, 9] },
  { code: 'PT', name: 'Portugal', dial: '+351', flag: '🇵🇹', lengths: [9, 9] },
  { code: 'PR', name: 'Puerto Rico', dial: '+1787', flag: '🇵🇷', lengths: [10, 10] },
  { code: 'QA', name: 'Qatar', dial: '+974', flag: '🇶🇦', lengths: [8, 8] },
  { code: 'RO', name: 'Romania', dial: '+40', flag: '🇷🇴', lengths: [9, 10] },
  { code: 'RU', name: 'Russia', dial: '+7', flag: '🇷🇺', lengths: [10, 10] },
  { code: 'RW', name: 'Rwanda', dial: '+250', flag: '🇷🇼', lengths: [9, 9] },
  { code: 'KN', name: 'Saint Kitts and Nevis', dial: '+1869', flag: '🇰🇳', lengths: [10, 10] },
  { code: 'LC', name: 'Saint Lucia', dial: '+1758', flag: '🇱🇨', lengths: [10, 10] },
  { code: 'VC', name: 'Saint Vincent and the Grenadines', dial: '+1784', flag: '🇻🇨', lengths: [10, 10] },
  { code: 'WS', name: 'Samoa', dial: '+685', flag: '🇼🇸', lengths: [7, 7] },
  { code: 'SM', name: 'San Marino', dial: '+378', flag: '🇸🇲', lengths: [10, 10] },
  { code: 'ST', name: 'Sao Tome and Principe', dial: '+239', flag: '🇸🇹', lengths: [7, 7] },
  { code: 'SA', name: 'Saudi Arabia', dial: '+966', flag: '🇸🇦', lengths: [9, 9] },
  { code: 'SN', name: 'Senegal', dial: '+221', flag: '🇸🇳', lengths: [9, 9] },
  { code: 'RS', name: 'Serbia', dial: '+381', flag: '🇷🇸', lengths: [8, 9] },
  { code: 'SC', name: 'Seychelles', dial: '+248', flag: '🇸🇨', lengths: [7, 7] },
  { code: 'SL', name: 'Sierra Leone', dial: '+232', flag: '🇸🇱', lengths: [8, 8] },
  { code: 'SG', name: 'Singapore', dial: '+65', flag: '🇸🇬', lengths: [8, 8] },
  { code: 'SK', name: 'Slovakia', dial: '+421', flag: '🇸🇰', lengths: [9, 9] },
  { code: 'SI', name: 'Slovenia', dial: '+386', flag: '🇸🇮', lengths: [8, 8] },
  { code: 'SB', name: 'Solomon Islands', dial: '+677', flag: '🇸🇧', lengths: [5, 7] },
  { code: 'SO', name: 'Somalia', dial: '+252', flag: '🇸🇴', lengths: [8, 9] },
  { code: 'KR', name: 'South Korea', dial: '+82', flag: '🇰🇷', lengths: [9, 10] },
  { code: 'SS', name: 'South Sudan', dial: '+211', flag: '🇸🇸', lengths: [9, 9] },
  { code: 'ES', name: 'Spain', dial: '+34', flag: '🇪🇸', lengths: [9, 9] },
  { code: 'LK', name: 'Sri Lanka', dial: '+94', flag: '🇱🇰', lengths: [9, 9] },
  { code: 'SD', name: 'Sudan', dial: '+249', flag: '🇸🇩', lengths: [9, 9] },
  { code: 'SR', name: 'Suriname', dial: '+597', flag: '🇸🇷', lengths: [6, 7] },
  { code: 'SE', name: 'Sweden', dial: '+46', flag: '🇸🇪', lengths: [7, 13] },
  { code: 'CH', name: 'Switzerland', dial: '+41', flag: '🇨🇭', lengths: [9, 9] },
  { code: 'SY', name: 'Syria', dial: '+963', flag: '🇸🇾', lengths: [9, 9] },
  { code: 'TW', name: 'Taiwan', dial: '+886', flag: '🇹🇼', lengths: [9, 9] },
  { code: 'TJ', name: 'Tajikistan', dial: '+992', flag: '🇹🇯', lengths: [9, 9] },
  { code: 'TZ', name: 'Tanzania', dial: '+255', flag: '🇹🇿', lengths: [9, 9] },
  { code: 'TH', name: 'Thailand', dial: '+66', flag: '🇹🇭', lengths: [9, 9] },
  { code: 'TL', name: 'Timor-Leste', dial: '+670', flag: '🇹🇱', lengths: [7, 8] },
  { code: 'TG', name: 'Togo', dial: '+228', flag: '🇹🇬', lengths: [8, 8] },
  { code: 'TO', name: 'Tonga', dial: '+676', flag: '🇹🇴', lengths: [5, 7] },
  { code: 'TT', name: 'Trinidad and Tobago', dial: '+1868', flag: '🇹🇹', lengths: [10, 10] },
  { code: 'TN', name: 'Tunisia', dial: '+216', flag: '🇹🇳', lengths: [8, 8] },
  { code: 'TR', name: 'Turkey', dial: '+90', flag: '🇹🇷', lengths: [10, 10] },
  { code: 'TM', name: 'Turkmenistan', dial: '+993', flag: '🇹🇲', lengths: [8, 8] },
  { code: 'TV', name: 'Tuvalu', dial: '+688', flag: '🇹🇻', lengths: [5, 6] },
  { code: 'UG', name: 'Uganda', dial: '+256', flag: '🇺🇬', lengths: [9, 9] },
  { code: 'UA', name: 'Ukraine', dial: '+380', flag: '🇺🇦', lengths: [9, 9] },
  { code: 'AE', name: 'United Arab Emirates', dial: '+971', flag: '🇦🇪', lengths: [9, 9] },
  { code: 'UY', name: 'Uruguay', dial: '+598', flag: '🇺🇾', lengths: [8, 8] },
  { code: 'UZ', name: 'Uzbekistan', dial: '+998', flag: '🇺🇿', lengths: [9, 9] },
  { code: 'VU', name: 'Vanuatu', dial: '+678', flag: '🇻🇺', lengths: [5, 7] },
  { code: 'VA', name: 'Vatican City', dial: '+379', flag: '🇻🇦', lengths: [10, 10] },
  { code: 'VE', name: 'Venezuela', dial: '+58', flag: '🇻🇪', lengths: [10, 10] },
  { code: 'VN', name: 'Vietnam', dial: '+84', flag: '🇻🇳', lengths: [9, 10] },
  { code: 'YE', name: 'Yemen', dial: '+967', flag: '🇾🇪', lengths: [9, 9] },
  { code: 'ZM', name: 'Zambia', dial: '+260', flag: '🇿🇲', lengths: [9, 9] },
  { code: 'ZW', name: 'Zimbabwe', dial: '+263', flag: '🇿🇼', lengths: [9, 9] },
];

const byDial = new Map();
COUNTRIES.forEach((c) => {
  if (!byDial.has(c.dial)) byDial.set(c.dial, c);
});
export const COUNTRIES_BY_DIAL = Object.fromEntries(byDial);

export function getCountryByDial(dial) {
  return COUNTRIES.find((c) => c.dial === dial) || COUNTRIES[0];
}

/** Get country by ISO code (e.g. 'CH', 'US'). */
export function getCountryByCode(code) {
  if (!code) return COUNTRIES[0];
  const upper = String(code).toUpperCase();
  return COUNTRIES.find((c) => c.code === upper) || COUNTRIES[0];
}
